name: Upload package to GitHub Releases

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Build
        run: go build -o rmm -v ./...

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./rmm
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref }}
          generate_release_notes: true
          draft: true
          prerelease: false
